AWSTemplateFormatVersion: 2010-09-09
Description: Template for Smart Meter Diagnostic Center Dashboard (SM006) Secrets 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Secret Manager Parameters
        Parameters:
          - SecretName
          - AppCode
          - AppName
      - Label:
          default: Registration
        Parameters:
          - OwnerContact
          - Requestor

################################## Parameters ################################################
Parameters:

  AppCode:
    Type: String
    MaxLength: "5"
    AllowedPattern: "^([A-Z0-9_-]){5}$"
    Description: The application code name cannot be of more that 5 characters, must be all CAP
    ConstraintDescription: Appcode field does not match the required constraints
    Default: ME005

  AppName:
    Type: String
    Description: Application name
    

  Requestor:
    Type: String
    Description: Please specify email address of the requestor
    AllowedPattern: '^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$'
    ConstraintDescription: Requestor field must be an email address
    Default: chiranjeev.singh@nexteraenergy.com

  OwnerContact:
    Type: String
    Description: Please specify email address of the owner
    AllowedPattern: '^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$'
    ConstraintDescription: "Requestor field must be an email address"
    Default: Baskaran.Sivasubramanian@fpl.com

  TeamName:
    Type: String
    Description: Please specify team name
    Default: Falcon

  SecretName:
    Type: String
    Description: Please specify Name for Your secret
    Default: Secrets
  
  REDSHIFTDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter Redshift EDP Dev Database Username'
    Default: amidashbdaws
    
  REDSHIFTDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter  Redshift EDP Dev Database Password'

  fcsOnOffCycleDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter fcsOnOffCycleDB Dev Database Username'
    Default: PWQUSER
     
  fcsOnOffCycleDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter  fcsOnOffCycleDB Dev Database Password'
  
  temperatureInfoDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter temperatureInfoDB Dev Database Username'
    Default: PWQUSER
     
  temperatureInfoDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter  temperatureInfoDB Dev Database Password'

  rcsEventDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter rcsEventDB Dev Database Username'
    Default: PWQUSER
     
  rcsEventDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter  rcsEventDB Dev Database Password'

  wmsDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter wmsDB Dev Database Username'
    Default: PWQUSER
     
  wmsDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter  wmsDB Dev Database Password'
  
  tktHstDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter tktHstDB Dev Database Username'
    Default: PWQUSER
     
  tktHstDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter tktHstDB Dev Database Password'

  tktCrntDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter tktCrntDB Dev Database Username'
    Default: PWQUSER
     
  tktCrntDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter tktCrntDB Dev Database Password'

  tcmsDispAndCustDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter tcmsDispAndCustDB Dev Database Username'
    Default: PWQUSER
     
  tcmsDispAndCustDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter tcmsDispAndCustDB Dev Database Password'

  fmosTktDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter fmosTktDB Dev Database Username'
    Default: PWQUSER
     
  fmosTktDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter fmosTktDB Dev Database Password'

  fpldwJdbcDBUser:
    Type: String
    NoEcho: false
    Description: 'Please Enter fpldwJdbcDB Dev Database Username'
    Default: CES_USER
     
  ffpldwJdbcDBPassword:
    Type: String
    NoEcho: true
    Description: 'Please Enter fpldwJdbcDB Dev Database Password'

Resources:
  MopsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AppSecret
      Description: !Sub "The app username which services use to access the ${AppName} database"
      SecretString: !Join
        - ''
        - - '{"redshift.edp.dev.username":"'
          - !Ref REDSHIFTDBUser
          - '","redshift.edp.password":"'
          - !Ref REDSHIFTDBPassword
          - '","fcs.OnOffCycle.username":"'
          - !Ref fcsOnOffCycleDBUser
          - '","fcs.OnOffCycle.password":"'
          - !Ref fcsOnOffCycleDBPassword
          - '","temperature.info.username":"'
          - !Ref temperatureInfoDBUser
          - '","temperature.info.password":"'
          - !Ref temperatureInfoDBPassword
          - '","rcs.Event.username":"'
          - !Ref rcsEventDBUser
          - '","rcs.Event.password":"'
          - !Ref rcsEventDBPassword
          - '","wms.db.username":"'
          - !Ref wmsDBUser
          - '","wms.db.password":"'
          - !Ref wmsDBPassword
          - '","tktHst.db.username":"'
          - !Ref tktHstDBUser
          - '","tktHst.db.password":"'
          - !Ref tktHstDBPassword
          - '","tktCrnt.db.username":"'
          - !Ref tktCrntDBUser
          - '","tktCrnt.db.password":"'
          - !Ref tktCrntDBPassword
          - '","tcm.dispAndCust.db.username":"'
          - !Ref tcmsDispAndCustDBUser
          - '","tcm.dispAndCust.db.password":"'
          - !Ref tcmsDispAndCustDBPassword
          - '","fmos.tkt.db.username":"'
          - !Ref fmosTktDBUser
          - '","fmos.tkt.db.password":"'
          - !Ref fmosTktDBPassword
          - '","fpl.dwJDBC.db.username":"'
          - !Ref fpldwJdbcDBUser
          - '","fpl.dwJDBC.db.password":"'
          - !Ref ffpldwJdbcDBPassword
          - '"}'
      Tags:
        - Key: AppCode
          Value: !Ref AppCode
        - Key: TeamName
          Value: !Ref TeamName
        - Key: Requestor
          Value: !Ref Requestor
        - Key: OwnerContact
          Value: !Ref OwnerContact

  SecretResourcePolicy: 
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref MopsSecret 
      ResourcePolicy: 
        Version: "2012-10-17" 
        Statement: 
          Effect: "Allow"
          Principal: 
            AWS: 
              - arn:aws:iam::188274256193:role/ecsTaskExecutionRole
          Action: 
            - "secretsmanager:GetSecretValue" 
            - "secretsmanager:RotateSecret"
          Resource: !Ref MopsSecret
Outputs:
  SecretName:
    Description: Secret ARN
    Value: !Ref MopsSecret
  
